[tool.poetry]
name = "chatsky-llm-autoconfiguration"
version = "0.1.0"
description = "Repository with all of the work related to Chatsky LLM-Autoconfig project"
authors = ["askatasuna <andruhabobr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
chatsky_llm_autoconfig = {path = "dev_packages/chatsky_llm_autoconfig", develop = true}
tqdm = "^4.66.5"
poethepoet = "^0.29.0"
pandas = "^2.2.3"
colorama = "^0.4.6"
pyarrow = "^18.0.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "*"
nbsphinx = "*"
sphinx-favicon = "*"
sphinx-gallery = "*"
sphinx-copybutton = "*"
sphinxcontrib-katex = "*"
pydata-sphinx-theme = "*"
sphinxcontrib-apidoc = "*"
sphinxcontrib-httpdomain = "*"
sphinx-autodoc-typehints = "*"
jupytext = "*"
jupyter = "*"

<<<<<<< HEAD

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

=======
>>>>>>> aa341269fece8d44c041cb7ff4e7857c4f7a83f7
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"





<<<<<<< HEAD


=======
>>>>>>> aa341269fece8d44c041cb7ff4e7857c4f7a83f7
[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
flake8 = "*"
isort = "*"
black = "*"
mypy = "*"




<<<<<<< HEAD


=======
>>>>>>> aa341269fece8d44c041cb7ff4e7857c4f7a83f7
[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
pytest = "*"

[tool.poe]
default_task_type = "script"

[tool.poe.tasks]
flake = "scripts.codestyle:_run_flake"
black = "scripts.codestyle:_run_black(modify=False)"
format = "scripts.codestyle:_run_black(modify=True)"
test = "scripts.test:_test"
metrics = "scripts.metrics:_run_check"
lint.sequence = ["flake", "black"]