name: documentation

on:
  push:
    branches:
    - dev
    - master
    - gh-pages
    - test/**
  pull_request:
    branches:
    - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/master' }}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: setup poetry and install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          python -m poetry install --no-ansi --no-interaction

      - name: Install documentation dependencies
        run: |
          poetry install --with docs

      - name: Sphinx build
        run: |
          poetry run sphinx-build docs/source docs/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
